name: Python CI Starter

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  pullcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: echo $uname
      run: echo $uname -a
  # TODO: add `pull_request` trigger targeting `main`
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: run pytest app 
        run: pytest test_app.py -v

      # TODO: install dependencies before running tests

      # TODO: run tests with `pytest test_app.py -v`

